--------------------------------------------------------
--  File created - Tuesday-May-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AR_CMDB_APPLICATION
--------------------------------------------------------

  CREATE TABLE "AR_CMDB_APPLICATION" 
   (	"ID" VARCHAR2(255 CHAR), 
	"LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"ISTATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SUBTYPE" VARCHAR2(255 CHAR), 
	"CG_ENVIRONMENT" VARCHAR2(255 CHAR), 
	"ASSIGNMENT" VARCHAR2(255 CHAR), 
	"VENDOR" VARCHAR2(255 CHAR), 
	"MODEL" VARCHAR2(255 CHAR), 
	"NETWORK_NAME" VARCHAR2(255 CHAR), 
	"SERIAL_NO_" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTAINER" VARCHAR2(255 CHAR), 
	"BUILDING" VARCHAR2(255 CHAR), 
	"SYSMODTIME" DATE, 
	"SYSMODUSER" VARCHAR2(255 CHAR), 
	"SITE_CATEGORY" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"UCMDB_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_BY_DATE" VARCHAR2(255 CHAR), 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR), 
	"CG_CREATEDATE" DATE, 
	"CG_CREATEDBY" VARCHAR2(255 CHAR), 
	"DOMAIN" VARCHAR2(255 CHAR), 
	"OPERATING_SYSTEM" VARCHAR2(255 CHAR), 
	"SERVER_ID" VARCHAR2(255 CHAR), 
	"MANUFACTURER" VARCHAR2(255 CHAR), 
	"IP_ADDRESS" VARCHAR2(255 CHAR), 
	"MAC_ADDRESS" VARCHAR2(255 CHAR), 
	"SUBNET_MASK" VARCHAR2(255 CHAR), 
	"DEFAULT_GATEWAY" VARCHAR2(255 CHAR), 
	"SUPPORT_GROUPS" VARCHAR2(255 CHAR), 
	"CG_SVC_TIER" VARCHAR2(255 CHAR), 
	"CG_CREATEDBY_FULLNAME" VARCHAR2(255 CHAR), 
	"CG_SERVICE_TIER" VARCHAR2(255 CHAR), 
	"CG_SYSTEM_TYPE" VARCHAR2(255 CHAR), 
	"CG_PRIMARYFUNCTION" VARCHAR2(255 CHAR)
   )
--------------------------------------------------------
--  DDL for Table AR_CMDB_APPLICATION_SERVER
--------------------------------------------------------

  CREATE TABLE "AR_CMDB_APPLICATION_SERVER" 
   (	"UPSTREAMCI_LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"DOWNSTREAMCI_LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"UPSTREAMCI_TYPE" VARCHAR2(255 CHAR), 
	"DOWNSTREAMCI_TYPE" VARCHAR2(255 CHAR), 
	"UPSTREAMCI_SUBTYPE" VARCHAR2(255 CHAR), 
	"DOWNSTREAMCI_SUBTYPE" VARCHAR2(255 CHAR), 
	"RELATIONSHIP_TYPE" VARCHAR2(255 CHAR), 
	"RELATIONSHIP_SUBTYPE" VARCHAR2(255 CHAR), 
	"STATUS" VARCHAR2(255 CHAR), 
	"UPSTREAMCI_ID" NUMBER, 
	"DOWNSTREAMCI_ID" VARCHAR2(255 CHAR), 
	"CREATE_DATETIME" DATE, 
	"UPDATE_DATETIME" DATE, 
	"UPSTREAMCI_UCMDB_ID" VARCHAR2(255 CHAR), 
	"DOWNSTREAMCI_UCMDB_ID" VARCHAR2(255 CHAR), 
	"RELATIONSHIP_NAME" VARCHAR2(255 CHAR)
   )
--------------------------------------------------------
--  DDL for Table AR_CMDB_DATABASE
--------------------------------------------------------

  CREATE TABLE "AR_CMDB_DATABASE" 
   (	"ID" VARCHAR2(255 CHAR), 
	"LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"ISTATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SUBTYPE" VARCHAR2(255 CHAR), 
	"CG_ENVIRONMENT" VARCHAR2(255 CHAR), 
	"ASSIGNMENT" VARCHAR2(255 CHAR), 
	"VENDOR" VARCHAR2(255 CHAR), 
	"MODEL" VARCHAR2(255 CHAR), 
	"NETWORK_NAME" VARCHAR2(255 CHAR), 
	"SERIAL_NO_" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTAINER" VARCHAR2(255 CHAR), 
	"BUILDING" VARCHAR2(255 CHAR), 
	"SYSMODTIME" DATE, 
	"SYSMODUSER" VARCHAR2(255 CHAR), 
	"SITE_CATEGORY" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"UCMDB_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_BY_DATE" VARCHAR2(255 CHAR), 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR), 
	"CG_CREATEDATE" DATE, 
	"CG_CREATEDBY" VARCHAR2(255 CHAR), 
	"DOMAIN" VARCHAR2(255 CHAR), 
	"OPERATING_SYSTEM" VARCHAR2(255 CHAR), 
	"SERVER_ID" VARCHAR2(255 CHAR), 
	"MANUFACTURER" VARCHAR2(255 CHAR), 
	"IP_ADDRESS" VARCHAR2(255 CHAR), 
	"MAC_ADDRESS" VARCHAR2(255 CHAR), 
	"SUBNET_MASK" VARCHAR2(255 CHAR), 
	"DEFAULT_GATEWAY" VARCHAR2(255 CHAR), 
	"SUPPORT_GROUPS" VARCHAR2(255 CHAR), 
	"CG_SVC_TIER" VARCHAR2(255 CHAR), 
	"CG_CREATEDBY_FULLNAME" VARCHAR2(255 CHAR), 
	"CG_SERVICE_TIER" VARCHAR2(255 CHAR), 
	"CG_SYSTEM_TYPE" VARCHAR2(255 CHAR), 
	"CG_PRIMARYFUNCTION" VARCHAR2(255 CHAR), 
	"LOCATION_CODE" VARCHAR2(100)
   )
--------------------------------------------------------
--  DDL for Table AR_CMDB_SERVER
--------------------------------------------------------

  CREATE TABLE "AR_CMDB_SERVER" 
   (	"ID" VARCHAR2(255 CHAR), 
	"LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"ISTATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SUBTYPE" VARCHAR2(255 CHAR), 
	"CG_ENVIRONMENT" VARCHAR2(255 CHAR), 
	"ASSIGNMENT" VARCHAR2(255 CHAR), 
	"VENDOR" VARCHAR2(255 CHAR), 
	"MODEL" VARCHAR2(255 CHAR), 
	"NETWORK_NAME" VARCHAR2(255 CHAR), 
	"SERIAL_NO_" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTAINER" VARCHAR2(255 CHAR), 
	"BUILDING" VARCHAR2(255 CHAR), 
	"SYSMODTIME" DATE, 
	"SYSMODUSER" VARCHAR2(255 CHAR), 
	"SITE_CATEGORY" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"UCMDB_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_BY_DATE" VARCHAR2(255 CHAR), 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR), 
	"CG_CREATEDATE" DATE, 
	"CG_CREATEDBY" VARCHAR2(255 CHAR), 
	"DOMAIN" VARCHAR2(255 CHAR), 
	"OPERATING_SYSTEM" VARCHAR2(255 CHAR), 
	"SERVER_ID" VARCHAR2(255 CHAR), 
	"MANUFACTURER" VARCHAR2(255 CHAR), 
	"IP_ADDRESS" VARCHAR2(255 CHAR), 
	"MAC_ADDRESS" VARCHAR2(255 CHAR), 
	"SUBNET_MASK" VARCHAR2(255 CHAR), 
	"DEFAULT_GATEWAY" VARCHAR2(255 CHAR), 
	"SUPPORT_GROUPS" VARCHAR2(255 CHAR), 
	"CG_SVC_TIER" VARCHAR2(255 CHAR), 
	"CG_CREATEDBY_FULLNAME" VARCHAR2(255 CHAR), 
	"CG_SERVICE_TIER" VARCHAR2(255 CHAR), 
	"CG_SYSTEM_TYPE" VARCHAR2(255 CHAR), 
	"CG_PRIMARYFUNCTION" VARCHAR2(255 CHAR), 
	"LOCATION_CODE" VARCHAR2(100)
   )
--------------------------------------------------------
--  DDL for Table AR_CMDB_STORAGE
--------------------------------------------------------

  CREATE TABLE "AR_CMDB_STORAGE" 
   (	"ID" VARCHAR2(255 CHAR), 
	"LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"ISTATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SUBTYPE" VARCHAR2(255 CHAR), 
	"CG_ENVIRONMENT" VARCHAR2(255 CHAR), 
	"ASSIGNMENT" VARCHAR2(255 CHAR), 
	"VENDOR" VARCHAR2(255 CHAR), 
	"MODEL" VARCHAR2(255 CHAR), 
	"NETWORK_NAME" VARCHAR2(255 CHAR), 
	"SERIAL_NO_" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTAINER" VARCHAR2(255 CHAR), 
	"BUILDING" VARCHAR2(255 CHAR), 
	"SYSMODTIME" DATE, 
	"SYSMODUSER" VARCHAR2(255 CHAR), 
	"SITE_CATEGORY" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"UCMDB_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_BY_DATE" VARCHAR2(255 CHAR), 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR), 
	"CG_CREATEDATE" DATE, 
	"CG_CREATEDBY" VARCHAR2(255 CHAR), 
	"DOMAIN" VARCHAR2(255 CHAR), 
	"OPERATING_SYSTEM" VARCHAR2(255 CHAR), 
	"SERVER_ID" VARCHAR2(255 CHAR), 
	"MANUFACTURER" VARCHAR2(255 CHAR), 
	"IP_ADDRESS" VARCHAR2(255 CHAR), 
	"MAC_ADDRESS" VARCHAR2(255 CHAR), 
	"SUBNET_MASK" VARCHAR2(255 CHAR), 
	"DEFAULT_GATEWAY" VARCHAR2(255 CHAR), 
	"SUPPORT_GROUPS" VARCHAR2(255 CHAR), 
	"CG_SVC_TIER" VARCHAR2(255 CHAR), 
	"CG_CREATEDBY_FULLNAME" VARCHAR2(255 CHAR), 
	"CG_SERVICE_TIER" VARCHAR2(255 CHAR), 
	"CG_SYSTEM_TYPE" VARCHAR2(255 CHAR), 
	"CG_PRIMARYFUNCTION" VARCHAR2(255 CHAR), 
	"LOCATION_CODE" VARCHAR2(100)
   )
--------------------------------------------------------
--  DDL for Table AR_DISCOVERY
--------------------------------------------------------

  CREATE TABLE "AR_DISCOVERY" 
   (	"HOST_NAME" VARCHAR2(120), 
	"NODE_KEY" VARCHAR2(120), 
	"HPE_BUSINESS" VARCHAR2(120), 
	"BUSINESS" VARCHAR2(120), 
	"SUB_BUSINESS" VARCHAR2(120), 
	"A_DOMAIN_NAME" VARCHAR2(120), 
	"OS_NAME" VARCHAR2(120), 
	"OSINSTALLTYPE" VARCHAR2(120), 
	"OSRELEASE" VARCHAR2(120), 
	"OSDESC" VARCHAR2(120), 
	"OS_VERSION" VARCHAR2(120), 
	"OSARCHITECTURE" VARCHAR2(120), 
	"OSVENDOR" VARCHAR2(120), 
	"OSFAMILY" VARCHAR2(120), 
	"VIRTUAL" VARCHAR2(1), 
	"VENDOR" VARCHAR2(120), 
	"DIS_MODEL" VARCHAR2(120), 
	"NODEVENDOR" VARCHAR2(120), 
	"NODEMODEL" VARCHAR2(120), 
	"CPU_NAME" VARCHAR2(120), 
	"SERIALNUMBER" VARCHAR2(300), 
	"MEMORY_SIZE" NUMBER, 
	"CPU_COUNT" NUMBER, 
	"CPU_SPEED" NUMBER, 
	"TOTAL_CPU_CORE" NUMBER, 
	"DISC_COUNT" NUMBER, 
	"DISKSIZE" NUMBER, 
	"INTERFACE_COUNT" NUMBER, 
	"LOCATION" VARCHAR2(300), 
	"GLOBAL_ID" VARCHAR2(120), 
	"CREATE_TIME" DATE, 
	"LASTACCESSTIME" DATE, 
	"MODIFIED_TIME" DATE, 
	"POLE" VARCHAR2(120), 
	"ACTIVE" VARCHAR2(1), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"SNOW_OS_ID" VARCHAR2(10), 
	"SNOW_OS_NAME" VARCHAR2(120), 
	"SNOW_MODEL_ID" VARCHAR2(10), 
	"SNOW_MODEL_NAME" VARCHAR2(120), 
	"BIOS_UUID" VARCHAR2(120), 
	"BIOS_VERSION" VARCHAR2(120), 
	"BIOS_DATE" VARCHAR2(120), 
	"DEFAULT_GATEWAY_IP_ADDRESS" VARCHAR2(240), 
	"PRIMARY_DNS_NAME" VARCHAR2(240)
   )
--------------------------------------------------------
--  DDL for Table AR_DISCOVERY2
--------------------------------------------------------

  CREATE TABLE "AR_DISCOVERY2" 
   (	"HOST_NAME" VARCHAR2(900), 
	"DIS_MODEL" VARCHAR2(250), 
	"A_DOMAIN_NAME" VARCHAR2(250), 
	"A_OS_VENDOR" VARCHAR2(200), 
	"OS_VERSION" VARCHAR2(500), 
	"VENDOR" VARCHAR2(250), 
	"OS_NAME" VARCHAR2(500), 
	"NODEMODEL" VARCHAR2(250), 
	"OSDESC" VARCHAR2(500), 
	"OSFAMILY" VARCHAR2(50), 
	"OSVENDOR" VARCHAR2(200), 
	"SERIALNUMBER" VARCHAR2(500), 
	"OSINSTALLTYPE" VARCHAR2(500), 
	"OSRELEASE" VARCHAR2(256), 
	"OSARCHITECTURE" VARCHAR2(50), 
	"NODEVENDOR" VARCHAR2(200), 
	"LOCATION" VARCHAR2(512), 
	"VIRTUAL" NUMBER(1,0), 
	"A_BIOS_DATE" NUMBER(22,0), 
	"A_BIOS_UUID" VARCHAR2(100), 
	"A_BIOS_VERSION" VARCHAR2(50), 
	"A_DEFAULT_GATEWAY_IP_ADDRESS" VARCHAR2(50), 
	"A_PRIMARY_DNS_NAME" VARCHAR2(250), 
	"GLOBAL_ID" RAW(16), 
	"A_MEMORY_SIZE" NUMBER(11,0), 
	"CREATE_TIME" NUMBER(22,0), 
	"MODIFIED_TIME" NUMBER(22,0), 
	"LASTACCESSTIME" NUMBER(22,0), 
	"CPU_NAME" VARCHAR2(900), 
	"CPU_SPEED" NUMBER, 
	"MAX_CPU_CORE" NUMBER, 
	"CPU_COUNT" NUMBER, 
	"DISK_SIZE" NUMBER, 
	"DISK_COUNT" NUMBER, 
	"INTERFACE_COUNT" NUMBER
   )
--------------------------------------------------------
--  DDL for Table AR_DISCOVERY_EXCEPTIONS
--------------------------------------------------------

  CREATE TABLE "AR_DISCOVERY_EXCEPTIONS" 
   (	"HOSTNAME" VARCHAR2(120), 
	"IP_ADDRESS" VARCHAR2(120), 
	"REASON" VARCHAR2(240), 
	"LOCATION" VARCHAR2(120), 
	"ACTIVE" VARCHAR2(1), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"IN_SCOPE" VARCHAR2(1)
   )
--------------------------------------------------------
--  DDL for Table AR_MAPPING_EXCEPTIONS
--------------------------------------------------------

  CREATE TABLE "AR_MAPPING_EXCEPTIONS" 
   (	"U_ASSET_ID" VARCHAR2(240), 
	"REASON" VARCHAR2(240), 
	"U_ASSET_CLASS" VARCHAR2(240), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"REASON_2" VARCHAR2(240), 
	"USER_INFO" VARCHAR2(50), 
	"EXCEPT_CONF_DATE" DATE
   )
--------------------------------------------------------
--  DDL for Table AR_METRICES
--------------------------------------------------------

  CREATE TABLE "AR_METRICES" 
   (	"METRIC_DATE" DATE, 
	"T_BUSINESS" VARCHAR2(100), 
	"T_SUB_BUSINESS" VARCHAR2(100), 
	"METRIC_NAME" VARCHAR2(50), 
	"METRIC_VALUE" VARCHAR2(50), 
	"METRIC_COUNT" NUMBER, 
	"METRIC_TOTAL" NUMBER
   )
--------------------------------------------------------
--  DDL for Table AR_METRIC_DEF
--------------------------------------------------------

  CREATE TABLE "AR_METRIC_DEF" 
   (	"METRIC_NAME" VARCHAR2(100), 
	"METRIC_TITLE" VARCHAR2(100), 
	"METRIC_ORDER" NUMBER, 
	"GROUP_NAME" VARCHAR2(100), 
	"GROUP_ORDER" NUMBER, 
	"DESCRIPTION" VARCHAR2(256), 
	"METRIC_TYPE" VARCHAR2(50), 
	"ACTIVE" CHAR(1)
   )
--------------------------------------------------------
--  DDL for Table AR_TEMP
--------------------------------------------------------

  CREATE TABLE "AR_TEMP" 
   (	"ID" VARCHAR2(255 CHAR), 
	"LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"ISTATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SUBTYPE" VARCHAR2(255 CHAR), 
	"CG_ENVIRONMENT" VARCHAR2(255 CHAR), 
	"ASSIGNMENT" VARCHAR2(255 CHAR), 
	"VENDOR" VARCHAR2(255 CHAR), 
	"MODEL" VARCHAR2(255 CHAR), 
	"NETWORK_NAME" VARCHAR2(255 CHAR), 
	"SERIAL_NO_" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTAINER" VARCHAR2(255 CHAR), 
	"BUILDING" VARCHAR2(255 CHAR), 
	"SYSMODTIME" DATE, 
	"SYSMODUSER" VARCHAR2(255 CHAR), 
	"SITE_CATEGORY" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"UCMDB_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_BY_DATE" VARCHAR2(255 CHAR), 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR), 
	"CG_CREATEDATE" DATE, 
	"CG_CREATEDBY" VARCHAR2(255 CHAR), 
	"DOMAIN" VARCHAR2(255 CHAR), 
	"OPERATING_SYSTEM" VARCHAR2(255 CHAR), 
	"SERVER_ID" VARCHAR2(255 CHAR), 
	"MANUFACTURER" VARCHAR2(255 CHAR), 
	"IP_ADDRESS" VARCHAR2(255 CHAR), 
	"MAC_ADDRESS" VARCHAR2(255 CHAR), 
	"SUBNET_MASK" VARCHAR2(255 CHAR), 
	"DEFAULT_GATEWAY" VARCHAR2(255 CHAR), 
	"SUPPORT_GROUPS" VARCHAR2(255 CHAR), 
	"CG_SVC_TIER" VARCHAR2(255 CHAR), 
	"CG_CREATEDBY_FULLNAME" VARCHAR2(255 CHAR), 
	"CG_SERVICE_TIER" VARCHAR2(255 CHAR), 
	"CG_SYSTEM_TYPE" VARCHAR2(255 CHAR), 
	"CG_PRIMARYFUNCTION" VARCHAR2(255 CHAR)
   )
--------------------------------------------------------
--  DDL for Table AR_XRP_SERVER
--------------------------------------------------------

  CREATE TABLE "AR_XRP_SERVER" 
   (	"ID" VARCHAR2(255 CHAR), 
	"LOGICAL_NAME" VARCHAR2(255 CHAR), 
	"ISTATUS" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR), 
	"SUBTYPE" VARCHAR2(255 CHAR), 
	"CG_ENVIRONMENT" VARCHAR2(255 CHAR), 
	"ASSIGNMENT" VARCHAR2(255 CHAR), 
	"VENDOR" VARCHAR2(255 CHAR), 
	"MODEL" VARCHAR2(255 CHAR), 
	"NETWORK_NAME" VARCHAR2(255 CHAR), 
	"SERIAL_NO_" VARCHAR2(255 CHAR), 
	"LOCATION" VARCHAR2(255 CHAR), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"CONTAINER" VARCHAR2(255 CHAR), 
	"BUILDING" VARCHAR2(255 CHAR), 
	"SYSMODTIME" DATE, 
	"SYSMODUSER" VARCHAR2(255 CHAR), 
	"SITE_CATEGORY" VARCHAR2(255 CHAR), 
	"OWNER" VARCHAR2(255 CHAR), 
	"UCMDB_ID" VARCHAR2(255 CHAR), 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_BY_DATE" VARCHAR2(255 CHAR), 
	"PRODUCT_VERSION" VARCHAR2(255 CHAR), 
	"CG_CREATEDATE" DATE, 
	"CG_CREATEDBY" VARCHAR2(255 CHAR), 
	"DOMAIN" VARCHAR2(255 CHAR), 
	"OPERATING_SYSTEM" VARCHAR2(255 CHAR), 
	"SERVER_ID" VARCHAR2(255 CHAR), 
	"MANUFACTURER" VARCHAR2(255 CHAR), 
	"IP_ADDRESS" VARCHAR2(255 CHAR), 
	"MAC_ADDRESS" VARCHAR2(255 CHAR), 
	"SUBNET_MASK" VARCHAR2(255 CHAR), 
	"DEFAULT_GATEWAY" VARCHAR2(255 CHAR), 
	"SUPPORT_GROUPS" VARCHAR2(255 CHAR), 
	"CG_SVC_TIER" VARCHAR2(255 CHAR), 
	"CG_CREATEDBY_FULLNAME" VARCHAR2(255 CHAR), 
	"CG_SERVICE_TIER" VARCHAR2(255 CHAR), 
	"CG_SYSTEM_TYPE" VARCHAR2(255 CHAR), 
	"CG_PRIMARYFUNCTION" VARCHAR2(255 CHAR), 
	"XRP_SOURCE" VARCHAR2(50), 
	"XRP_LOAD_DATE" DATE, 
	"LOCATION_CODE" VARCHAR2(100)
   )
